(define (problem p2)
    (:domain hanoi)
    (:objects K1 K2 K3 K4 K5 - krazek)
    (:init
        (mniejszy K1 K2)
        (mniejszy K1 K3)
        (mniejszy K1 K4)
        (mniejszy K1 K5)
        (mniejszy K2 K3)
        (mniejszy K2 K4)
        (mniejszy K2 K5)
        (mniejszy K3 K4)
        (mniejszy K3 K5)
        (mniejszy K4 K5)
        (na x K5)
        (na x K4)
        (na x K3)
        (na x K2)
        (na x K1)
    )
    (:goal
        (and
            (na z K5)
            (na z K4)
            (na z K3)
            (na z K2)
            (na z K1)
        )
    )
)