package com.sample

import com.sample.DroolsTest.Plec;
import com.sample.DroolsTest.Osoba;
import com.sample.DroolsTest.Relacja;

rule "Init"
	when
	then
		Osoba maria          = new Osoba("Maria");
		Osoba ewa            = new Osoba("Ewa");
		Osoba agata          = new Osoba("Agata");
		Osoba anna           = new Osoba("Anna");
		Osoba agnieszka      = new Osoba("Agnieszka");
		Osoba beata          = new Osoba("Beata");
		Osoba iwona          = new Osoba("Iwona");
		Osoba joanna         = new Osoba("Joanna");
		Osoba piotr          = new Osoba("Piotr");
		Osoba adam           = new Osoba("Adam");
		Osoba marek          = new Osoba("Marek");
		Osoba robert         = new Osoba("Robert");
		Osoba jan            = new Osoba("Jan");
		Osoba krzysztof      = new Osoba("Krzysztof");
		Osoba radek          = new Osoba("Radek");
		Osoba darek          = new Osoba("Darek");
		Osoba tomek          = new Osoba("Tomek");
		Osoba jacek          = new Osoba("Jacek");

		insert(new Relacja(maria,marek,"rodzic"));
		insert(new Relacja(maria,agata,"rodzic"));
		insert(new Relacja(maria,jan,"rodzic"));
		insert(new Relacja(piotr,marek,"rodzic"));
		insert(new Relacja(piotr,agata,"rodzic"));
		insert(new Relacja(piotr,jan,"rodzic"));
		insert(new Relacja(ewa,anna,"rodzic"));
		insert(new Relacja(ewa,joanna,"rodzic"));
		insert(new Relacja(ewa,krzysztof,"rodzic"));
		insert(new Relacja(adam,anna,"rodzic"));
		insert(new Relacja(adam,joanna,"rodzic"));
		insert(new Relacja(adam,krzysztof,"rodzic"));
		insert(new Relacja(agata,radek,"rodzic"));
		insert(new Relacja(agata,beata,"rodzic"));
		insert(new Relacja(robert,radek,"rodzic"));
		insert(new Relacja(robert,beata,"rodzic"));
		insert(new Relacja(anna,darek,"rodzic"));
		insert(new Relacja(anna,tomek,"rodzic"));
		insert(new Relacja(jan,darek,"rodzic"));
		insert(new Relacja(jan,tomek,"rodzic"));
		insert(new Relacja(agnieszka,jacek,"rodzic"));
		insert(new Relacja(agnieszka,iwona,"rodzic"));
		insert(new Relacja(krzysztof,jacek,"rodzic"));
		insert(new Relacja(krzysztof,iwona,"rodzic"));
end

rule "Kobieta0"
    when
        Relacja(osoby[0].imie matches "(.)+a$", osoby[0].plec == Plec.NIEZNANA, o : osoby[0])
    then
    	o.plec = Plec.KOBIETA;
    	for(int i = 0; i < o.relacje.size(); i++){
    		update(o.relacje.get(i));
    	}
end

rule "Kobieta1"
    when
        Relacja(osoby[1].imie matches "(.)+a$", osoby[1].plec == Plec.NIEZNANA, o : osoby[1])
    then
    	o.plec = Plec.KOBIETA;
    	for(int i = 0; i < o.relacje.size(); i++){
    		update(o.relacje.get(i));
    	}
end

rule "Mezczyzna0"
    when
        Relacja(osoby[0].imie not matches "(.)+a$", osoby[0].plec == Plec.NIEZNANA, o : osoby[0])
    then
    	o.plec = Plec.MEZCZYZNA;
    	for(int i = 0; i < o.relacje.size(); i++){
    		update(o.relacje.get(i));
    	}
end

rule "Mezczyzna1"
    when
        Relacja(osoby[1].imie not matches "(.)+a$", osoby[1].plec == Plec.NIEZNANA, o : osoby[1])
    then
    	o.plec = Plec.MEZCZYZNA;
    	for(int i = 0; i < o.relacje.size(); i++){
    		update(o.relacje.get(i));
    	}
end