(define (problem merryp)
    (:domain merry)
    (:objects a b c d e f g h i - pokoj
              niebieski pomaranczowy czerwony zielony rozowy - kolor
              k1 k2 k3 k4 k5 k6 k7 k8 - klocek
              p1 p2 p3 p4 p5 p6 p7 p8 p9 - pole
              ka1 kb1 kc1 kc2 kd1 kd2 ke1 ke2 kf1 kf2 kh1 kh2 ki1 ki2 - kulka
    )   
    (:init
        (poziomo a b pomaranczowy)
        (poziomo e f niebieski)
        (poziomo f e niebieski)
        (poziomo f g rozowy)
        (poziomo h i niebieski)
        (poziomo i h niebieski)

        (pionowo a c czerwony)
        (pionowo c a czerwony)
        (pionowo c e zielony)
        (pionowo e c zielony)
        (pionowo e h czerwony)
        (pionowo h e czerwony)
        (pionowo b d pomaranczowy)
        (pionowo d f zielony)
        (pionowo f d zielony)
        (pionowo f i niebieski)
        (pionowo i f niebieski)

        (w a ka1 zielony)
        (w b kb1 rozowy)
        (w c kc1 pomaranczowy)
        (w c kc2 niebieski)
        (w d kd1 zielony)
        (w d kd2 czerwony)
        (w e ke1 niebieski)
        (w e ke2 zielony)
        (w f kf1 niebieski)
        (w f kf2 niebieski)
        (w h kh1 zielony)
        (w h kh2 czerwony)
        (w i ki1 pomaranczowy)
        (w i ki2 niebieski)

        (wbk a ka1)
        (wbk b kb1)
        (wbk c kc1)
        (wbk c kc2)
        (wbk d kd1)
        (wbk d kd2)
        (wbk e ke1)
        (wbk e ke2)
        (wbk f kf1)
        (wbk f kf2)
        (wbk h kh1)
        (wbk h kh2)
        (wbk i ki1)
        (wbk i ki2)

        (czlowiek f)

        (na p1 k5)
        (na p2 k4)
        (na p3 k1)
        (na p4 k8)
        (na p6 k3)
        (na p7 k7)
        (na p8 k2)
        (na p9 k6)

        (sasiad p1 p2)
        (sasiad p2 p1)
        (sasiad p2 p3)
        (sasiad p3 p2)
        (sasiad p4 p5)
        (sasiad p5 p4)
        (sasiad p5 p6)
        (sasiad p6 p5)
        (sasiad p7 p8)
        (sasiad p8 p7)
        (sasiad p8 p9)
        (sasiad p9 p8)
        (sasiad p1 p4)
        (sasiad p4 p1)
        (sasiad p4 p7)
        (sasiad p7 p4)
        (sasiad p2 p5)
        (sasiad p5 p2)
        (sasiad p5 p8)
        (sasiad p8 p5)
        (sasiad p3 p6)
        (sasiad p6 p3)
        (sasiad p6 p9)
        (sasiad p9 p6)
    )
    (:goal
        (and
            (na p1 k1)
            (na p2 k2)
            (na p3 k3)
            (na p4 k4)
            (na p5 k5)
            (na p6 k6)
            (na p7 k7)
            (na p8 k8)
            (czlowiek g)
        );
    )
)