(define (problem rozsypanka)
    (:domain blocks)
    (:objects a b c d e f g h)
    (:init
            (na_ziemi a)
            (na_ziemi b)
            (na_ziemi c)
            (na_ziemi d)
            (na_ziemi e)
            (na_ziemi f)
            (na_ziemi g)
            (na_ziemi h)
            (wolny a)
            (wolny b)
            (wolny c)
            (wolny d)
            
            (wolny e)
            (wolny f)
            (wolny g)
            (wolny h)
    )
    (:goal
        (and
            (na_ziemi h)
            (na g h)
            (na f g)
            (na e f)
            (na d e)
            (na c d)
            (na b c)
            (na a b)
        )
    )
)