package com.sample
 
import com.sample.DroolsTest.Pomiar;
import com.sample.DroolsTest.Pozar;
import com.sample.DroolsTest.Telefon;
import com.sample.DroolsTest.Straz;


rule "init"
	when
	
	then
		insert(new Pomiar(false, 140));
		insert(new Pomiar(false, 151));
end

rule "Pozar"
	when
		exists Pomiar(dym == true || temperatura > 150) 
	then
		insert(new Pozar());
end

rule "Komunikat"
	when
		Pozar()
	then
		System.out.println("Pali sie");
end

rule "Telefon"
	when
		Pozar()
	then
		insert(new Telefon(112));
end

rule "Zadzwon"
	when 
		tel: Telefon()
	then
		System.out.println("Prosze zadzwonic na " + tel.number);
		// update(tel); tel wraca do pamięci
end

rule "Straz"
	when
		Straz()
		pozar: Pozar()
	then
		System.out.println("Straz przyjechala!");
		retract(pozar);
end

rule "Odjazd strazy"
	when
		straz: Straz()
		not Pozar()
	then
		retract(straz);
		System.out.println("Straz odjechala.");
end









		
